name: yoga_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  icons_launcher: ^3.0.0
  rename: ^3.0.2
  flick_video_player: ^0.9.0
  video_player: ^2.9.1
  flutter_inappwebview: ^6.1.0+1
  youtube_player_flutter: ^9.1.0
  equatable: ^2.0.5
  bloc: ^8.1.4
  hive: ^2.2.3
  path_provider: ^2.1.4
  provider: ^6.1.2
  flutter_bloc: ^8.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/pose/
    - assets/icons/

  fonts:
     - family: Manrope
       fonts:
         - asset: assets/fonts/Manrope/Manrope-Bold.ttf
         - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
         - asset: assets/fonts/Manrope/Manrope-ExtraLight.ttf
         - asset: assets/fonts/Manrope/Manrope-Light.ttf
         - asset: assets/fonts/Manrope/Manrope-Medium.ttf
         - asset: assets/fonts/Manrope/Manrope-Regular.ttf
         - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf


icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true